//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Donate_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string area { get; set; }
        public string district { get; set; }
    }
}
