//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Donate_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string userName { get; set; }
        public string firstName { get; set; }
        public string surName { get; set; }
        public string sex { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string bloodGroup { get; set; }
        public string mobileNo { get; set; }
        public string area { get; set; }
    }
}
